version: "3.7"
services:
  web:
    build:
      target: development
    ports:
      - 8081:8080
    volumes:
      - ./.:/project
      - /project/node_modules
    labels:
      kompose.service.type: nodeport
