name: Build and Push Docker Image for Web App

on:
  push:
    tags: ["*"]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true

      - name: Extract metadata (tags, labels) for Docker API
        id: meta_fe
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/vdt-fe

      - name: Build and Push Docker API Image
        uses: docker/build-push-action@v4
        id: docker_db
        with:
          context: .
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/arm64,linux/amd64
          push: true
          tags: ${{ steps.meta_fe.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Checkout config repo
        uses: actions/checkout@v3
        with:
          repository: lmhuong711/go-go-fe-config
          token: ${{ secrets.CONFIG_REPO_TOKEN }}

      - name: Update vdt-fe image in dev-values.yaml
        run: |
          sed -i "s|tag:.*|tag: \"${{ github.ref_name }}\"|g" dev-values.yaml
          git config --global user.email "lmhuong711@gmail.com"
          git config --global user.name "lmhuong711"
          git add dev-values.yaml
          git commit -m "Update vdt-api image to ${{ secrets.DOCKERHUB_USERNAME }}/vdt-api:${{ github.ref_name }}"
          git push
